## Race data for 331 US artists represented in the Tate Modern
col_names <- c("name", "race")

race <- data.frame(matrix(ncol = 2, nrow = 0))

race <- rbind(race, c("Abbey, Edwin Austin", "White"))
race <- rbind(race, c("Abbott, Berenice", "White"))
race <- rbind(race, c("Acconci, Vito", "White"))
race <- rbind(race, c("Albright, Ivan", "White"))
race <- rbind(race, c("Allora, Jennifer", "White"))
race <- rbind(race, c("Altoon, John" , "White"))
race <- rbind(race, c("Andre, Carl" , "White"))
race <- rbind(race, c("Antin, Eleanor" , "White"))
race <- rbind(race, c("Anuszkiewicz, Richard" , "White"))
race <- rbind(race, c("Arbus, Diane"  , "White"))
race <- rbind(race, c("Arcangel, Cory" , "White"))
race <- rbind(race, c("Artschwager, Richard" , "White"))
race <- rbind(race, c("Atlas, Charles"  , "White"))
race <- rbind(race, c("Avedon, Richard"  , "White"))
race <- rbind(race, c("Avery, Milton" , "White"))
race <- rbind(race, c("Baer, Jo" , "White"))
race <- rbind(race, c("Baldessari, John"  , "White"))
race <- rbind(race, c("Ballen, Roger"  , "White"))
race <- rbind(race, c("Baltz, Lewis" , "White"))
race <- rbind(race, c("Barney, Matthew" , "White"))
race <- rbind(race, c("Bartlett, Jennifer", "White"))
race <- rbind(race, c("Baskin, Leonard", "White"))
race <- rbind(race, c("Baynard, Ed", "White"))
race <- rbind(race, c("Baziotes, William" , "White"))
race <- rbind(race, c("Beckley, Bill", "White"))
race <- rbind(race, c("Bell, Larry" , "White"))
race <- rbind(race, c("Benglis, Lynda", "White"))
race <- rbind(race, c("Berthot, Jake" , "White"))
race <- rbind(race, c("Biederman, Charles", "White"))
race <- rbind(race, c("Blake, John" , "Unknown"))
race <- rbind(race, c("Bleckner, Ross", "White"))
race <- rbind(race, c("Bochner, Mel" , "White"))
race <- rbind(race, c("Bontecou, Lee", "White"))
race <- rbind(race, c("Borofsky, Jonathan" , "White"))
race <- rbind(race, c("Boxer, Stanley", "White"))
race <- rbind(race, c("Bradford, Mark" , "Black"))
race <- rbind(race, c("Brooks, James", "White"))
race <- rbind(race, c("Buckingham, Matthew", "White"))
race <- rbind(race, c("Burchfield, Charles", "White"))
race <- rbind(race, c("Burden, Chris" , "White"))
race <- rbind(race, c("Burkert, Robert", "White"))
race <- rbind(race, c("Burton, Scott", "White"))
race <- rbind(race, c("Cage, John", "White"))
race <- rbind(race, c("Cain, Neville" , "White"))
race <- rbind(race, c("Calder, Alexander" , "White"))
race <- rbind(race, c("Callahan, Harry" , "White"))
race <- rbind(race, c("Campus, Peter" , "White"))
race <- rbind(race, c("Cantor, Ellen" , "White"))
race <- rbind(race, c("Carter, Nathan" , "White"))
race <- rbind(race, c("Casebere, James" , "White"))
race <- rbind(race, c("Chamberlain, John" , "White"))
race <- rbind(race, c("Close, Chuck" , "White"))
race <- rbind(race, c("Cohen, Lynne"  , "White"))
race <- rbind(race, c("Colescott, Warrington"  , "White"))
race <- rbind(race, c("Collier, Anne"  , "White"))
race <- rbind(race, c("Cooper, Thomas Joshua"  , "White"))
race <- rbind(race, c("Copley, John Singleton"  , "White"))
race <- rbind(race, c("Copley, William N.", "White"))
race <- rbind(race, c("Cornell, Joseph", "White"))
race <- rbind(race, c("Cottingham, Robert", "White"))
race <- rbind(race, c("Crutchfield, William", "White"))
race <- rbind(race, c("Currin, John", "White"))

"D'Arcangelo, Allan"             "Davidson, Bruce"               
[65] "Davis, Gene"                    "Davis, Ron"                     "Davis, Stuart"                  "De Rivera, José"               
[69] "Dehn, Adolf"                    "DeLap, Tony"                    "Deverell, Walter Howell"        "Diebenkorn, Richard"           
[73] "Dine, Jim"                      "Dion, Mark"                     "Donnelly, Trisha"               "Downsbrough, Peter"            
[77] "Drew, Leonardo"                 "Dugger, John"                   "Dunham, Carroll"                "Durant, Sam"                   
[81] "Durham, Jimmie"

colnames(race) <- col_names
